export const FORMATOS_QA = [
  {
    id: 'qa_adicion_telefonos_capacitacion',
    nombre: 'Acta QA adición de teléfonos y capacitación',
    archivo: 'FOR Acta QA adición de teléfonos y capacitación.docx',
    descripcion: 'Formato para adición de teléfonos y capacitación.',
    icon: 'ti-phone-plus',
  },
  {
    id: 'qa_hotspots',
    nombre: 'Acta QA HOTSPOTS',
    archivo: 'FOR Acta QA HOTSPOTS.docx',
    descripcion: 'Formato para validación de servicios HOTSPOTS.',
    icon: 'ti-wifi',
  },
  {
    id: 'qa_instalacion_wlan',
    nombre: 'Acta QA Instalación WLAN',
    archivo: 'FOR Acta QA Instalación WLAN.docx',
    descripcion: 'Formato para instalación WLAN.',
    icon: 'ti-router',
  },
  {
    id: 'qa_internet_dedicado_empresarial',
    nombre: 'Acta QA Internet dedicado empresarial',
    archivo: 'FOR Acta QA Internet dedicado empresarial.docx',
    descripcion: 'Formato para internet dedicado empresarial.',
    icon: 'ti-building-broadcast-tower',
  },
  {
    id: 'qa_internet_dedicado_front_end',
    nombre: 'Acta QA Internet dedicado Front end',
    archivo: 'FOR Acta QA Internet dedicado Front end.docx',
    descripcion: 'Formato para internet dedicado Front end.',
    icon: 'ti-world',
  },
  {
    id: 'qa_internet_seguro_corporativo',
    nombre: 'Acta QA Internet Seguro Corporativo',
    archivo: 'FOR Acta QA Internet Seguro Corporativo.docx',
    descripcion: 'Formato para internet seguro corporativo.',
    icon: 'ti-shield-check',
  },
  {
    id: 'qa_ip_data',
    nombre: 'Acta QA IP Data',
    archivo: 'FOR Acta QA IP Data.docx',
    descripcion: 'Formato para servicios IP Data.',
    icon: 'ti-network',
  },
  {
    id: 'qa_mpls',
    nombre: 'Acta QA MPLS',
    archivo: 'FOR Acta QA MPLS.docx',
    descripcion: 'Formato actual para servicios MPLS.',
    icon: 'ti-cloud-network',
  },
  {
    id: 'qa_pls_ipl',
    nombre: 'Acta QA PLS-IPL',
    archivo: 'FOR Acta QA PLS-IPL.docx',
    descripcion: 'Formato para servicios PLS/IPL.',
    icon: 'ti-route',
  },
  {
    id: 'qa_protocolo_pruebas_backup',
    nombre: 'Acta QA Protocolo pruebas backup',
    archivo: 'FOR Acta QA Protocolo pruebas backup.docx',
    descripcion: 'Formato para protocolo de pruebas de backup.',
    icon: 'ti-database-export',
  },
  {
    id: 'qa_servicios_internet_telefonia_ultrawifi_mpls',
    nombre: 'Acta QA Servicios internet telefonía ultrawifi y MPLS',
    archivo: 'FOR Acta QA Servicios internet telefonia ultrawifi y MPLS.docx',
    descripcion: 'Formato para servicios integrados de internet, telefonía, ultrawifi y MPLS.',
    icon: 'ti-devices',
  },
  {
    id: 'qa_site_survey_lan_administrada',
    nombre: 'Acta QA site survey LAN administrada',
    archivo: 'FOR Acta QA site survey Lan administrada.docx',
    descripcion: 'Formato para site survey LAN administrada.',
    icon: 'ti-clipboard-search',
  },
  {
    id: 'qa_site_survey_wlan',
    nombre: 'Acta QA site survey WLAN',
    archivo: 'FOR Acta QA site survey WLAN.docx',
    descripcion: 'Formato para site survey WLAN.',
    icon: 'ti-wifi-2',
  },
  {
    id: 'qa_sw_lan_administrada',
    nombre: 'Acta QA SW LAN administrada',
    archivo: 'FOR Acta QA SW Lan administrada.docx',
    descripcion: 'Formato para switch LAN administrada.',
    icon: 'ti-server',
  },
  {
    id: 'qa_telefonia_analoga_basica',
    nombre: 'Acta QA Telefonía Análoga Básica',
    archivo: 'FOR Acta QA Telefonía Análoga Básica.docx',
    descripcion: 'Formato para telefonía análoga básica.',
    icon: 'ti-phone',
  },
  {
    id: 'qa_telefonia_digital_e1',
    nombre: 'Acta QA Telefonía digital E1',
    archivo: 'FOR Acta QA Telefonía digital E1.docx',
    descripcion: 'Formato para telefonía digital E1.',
    icon: 'ti-phone-call',
  },
  {
    id: 'qa_telefonia_pbx_administrada',
    nombre: 'Acta QA Telefonía PBX Administrada',
    archivo: 'FOR Acta QA Telefonía PBX Administrada.docx',
    descripcion: 'Formato para telefonía PBX administrada.',
    icon: 'ti-phone-calling',
  },
  {
    id: 'qa_telefonia_troncal_sip_gateway_centralizada',
    nombre: 'Acta QA Telefonía Troncal SIP Gateway y Centralizada',
    archivo: 'FOR Acta QA Telefonía Troncal SIP Gateway y Centralizada.docx',
    descripcion: 'Formato para troncal SIP, gateway y telefonía centralizada.',
    icon: 'ti-antenna-bars-5',
  },
  {
    id: 'qa_videoconferencia',
    nombre: 'Acta QA Videoconferencia',
    archivo: 'FOR Acta QA Videoconferencia.docx',
    descripcion: 'Formato para servicios de videoconferencia.',
    icon: 'ti-video',
  },
];

export const getFormatoQaById = (id) => {
  return FORMATOS_QA.find(f => f.id === id) || FORMATOS_QA.find(f => f.id === 'qa_mpls');
};